######################################################################
# Automatically generated by qmake (3.0) ?? 10? 29 15:34:37 2017
######################################################################

QT += core gui widgets

TEMPLATE = app
TARGET = QNavigationWidget
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h qnavigationwidget.h
SOURCES += main.cpp mainwindow.cpp qnavigationwidget.cpp
